### PR TITLE
dy174

### PR DESCRIPTION
**Pull request by yfiring**
I think (after main_clean2 is merged into main) the remaining differences should be resolved in favour of the dy174 version. They have all been used on dy174 (and/or en705) and contain updates to: 
a) use global MOORPROC_G and cleaner ways of setting paths; 
b) use more vectors rather than loops (for setting/selecting from lists of id numbers etc.);
c) not rely on (Matlab-version-dependent) datetime handling to convert to julian day

### CODE REVIEW

**Review by Kristin-2002 — APPROVED** [review]
I agree with the changes.

**Review by Kristin-2002 — APPROVED** [review]

**Comment by Kristin-2002** [comment]
@yfiring here I would need a review. It is the same pull request but I updated the pull request, so now you need to approve.
Thank you

**Review by yfiring — COMMENTED** [review]
accepted

**Review by yfiring — COMMENTED** [review]
I can't approve, though (as the pull request author)

**Pull request closed without merging**
